name: Build py

# When the workflow will run
on:
  # Triggers the workflow on push or pull request (only for the "main" branche)
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually
  workflow_dispatch:

# Includes tasks to be completed
jobs:
  # Builds app
  build:
    # Is OS that the job will run on
    runs-on: windows-latest
    
    # Includes tasks and their description
    steps:
      # Checkout repository from Git
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Sets up version of Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      # Installs dependencies from file requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create archive
      - name: Archive
        run: 7z a archive.7z main.py

      # Uploads artefact
      - name: Upload a Build Artefact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: py-app
          path: archive.7z

